sudo: required
services:
  - docker

before_install:
  - docker build -t f1oop/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true f1oop/docker-test npm run test -- --coverage

after_success:
  - docker build -t f1oop/multi-client ./client
  - docker build -t f1oop/multi-nginx ./ngnix
  - docker build -t f1oop/multi-server ./server
  - docker build -t f1oop/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# take those imaged and push them to docker hub
  - docker push f1oop/multi-client
  - docker push f1oop/multi-ngnix
  - docker push f1oop/multi-server
  - docker push f1oop/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-eu-north-1-598444950095
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
